name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup Crystal 0.34.0
      uses: oprypin/install-crystal@v1
      with:
        crystal: 0.34.0
    - name: Setup .env
      run: cp .env.ci .env.test
    - name: Install dependencies
      run: shards install
    - name: Static analysis
      run: ./bin/ameba
    - name: Run tests
      run: KEMAL_ENV=test crystal spec